apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-volume-01
  labels: 
    app: hdfs-k8s.namenode
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/USER/namenode01"
